import Component from "@/src/components/Component";
import Head from "next/head";
import React from "react";

export default function shubham() {
  return (
    <>
      <Head>
        <title>Shubham</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Component />
      </div>
    </>
  );
}
